#!/usr/bin/env python

import sys
import getopt

alpha_listing="""IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  www.example.com:http         rr
  -> google.com:http              Masq    1      0          0
  -> slashdot.org:http            Masq    1      0          0
UDP  example.org:domain           rr
  -> resolver1.opendns.com:domain Masq    1      0          0
  -> resolver1.opendns.com:domain Masq    1      0          0"""

numeric_listing="""IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.0.43.10:80               rr
  -> 173.194.43.3:80              Masq    1      0          0
  -> 216.34.181.45:80             Masq    1      0          0
UDP  192.0.43.10:53               rr
  -> 208.67.222.222:53            Masq    1      0          0
  -> 208.67.220.220:53            Masq    1      0          0"""

def main():
  try:
    opts, args = getopt.getopt(sys.argv[1:], "Lnt:u:f:",
                               ["list"])
  except getopt.error, msg:
    print msg
    sys.exit(1)
  listing = True
  tcp = False
  udp = False
  fwm = False
  full_listing = alpha_listing
  for opt, arg in opts:
    if opt in ("-L", "--list"):
      listing = True
    elif opt == "-t":
      if (arg == "www.example.com:80" or arg == "192.0.43.10:80"
          or arg == "www.example.com:http"):
        tcp = True
    elif opt == "-u":
      if (arg == "example.org:53" or arg == "192.0.43.10:53"
          or arg == "example.org:domain"):
        udp = True
    elif opt == "-f":
      fwm = True
    elif opt == "-n":
      full_listing = numeric_listing


  list_items = full_listing.split("\n")
  if tcp:
    for item in list_items[:6]:
      print item
  elif udp:
    for item in list_items[:3]:
      print item
    for item in list_items[6:]:
      print item
  elif listing:
    print full_listing

if __name__ == '__main__':
  main()
